academiaapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path('categorias/', include('categories.urls', namespace='categories')),
    path('aparelhos/', include('aparelhos.urls', namespace='aparelhos')),
    path('treinadores/', include('treinadores.urls', namespace='treinadores')),
    path('academias/', include('academias.urls', namespace='academias')),
    path('contas/', include('accounts.urls', namespace='accounts')),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/academias/urls.py
from django.urls import path
from . import views

app_name = 'academias'

urlpatterns = [
    path('', views.list_academias, name='list_academias'),
    path('adicionar/', views.add_academia, name='add_academia'),
    path('editar/<int:id_academia>/', views.edit_academia, name='edit_academia'),
    path('excluir/<int:id_academia>/', views.delete_academia, name='delete_academia'),
]

apps/academias/models.py
from django.db import models
from categories.models import Category
from treinadores.models import Treinador

# Create your models here.
class Academia(models.Model):
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    name = models.CharField('Nome', max_length=50)
    address = models.CharField('Endereco', max_length=200)   
    cidade = models.CharField('Cidade', max_length=200)
    academia_category = models.ManyToManyField(Category, through='AcademiaCategory', blank=True)
    academia_treinador = models.ManyToManyField(Treinador, through='AcademiaTreinador', blank=True)

    class Meta:
        verbose_name = 'Academia'
        verbose_name_plural = 'Academias'
        ordering =['id']

    def __str__(self):
        return self.name


class AcademiaCategory(models.Model):
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    academia = models.ForeignKey(Academia, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Item de Categoria'
        verbose_name_plural = 'Itens de Categoria'
        ordering =['id']

    def __str__(self):
        return self.category.name

class AcademiaTreinador(models.Model):
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    academia = models.ForeignKey(Academia, on_delete=models.CASCADE)
    treinador = models.ForeignKey(Treinador, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Item de Treinador'
        verbose_name_plural = 'Itens de Treinador'
        ordering =['id']

    def __str__(self):
        return self.treinador.name

apps/academias/forms.py
from django import forms
from .models import Academia

class AcademiaForm(forms.ModelForm):

    class Meta:
        model = Academia
        exclude = ('created_on' , 'updated_on',)

apps/academias/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .forms import AcademiaForm
from .models import Academia, Category, Treinador, AcademiaCategory, AcademiaTreinador
from django.contrib.auth.decorators import login_required

@login_required(login_url='/contas/login/')
def add_academia(request):
    template_name = 'academias/add_academia.html'
    context = {}
    if request.method == 'POST':
        form = AcademiaForm(request.POST)
        if form.is_valid():
            f = form.save(commit=False)
            f.save()
            form.save_m2m()
            return redirect('academias:list_academias')
    form = AcademiaForm()
    context['form'] = form
    return render(request, template_name, context)

def list_academias(request):
    template_name = 'academias/list_academias.html'
    academia_categories = AcademiaCategory.objects.filter()
    academia_treinadores = AcademiaTreinador.objects.filter()
    categories = Category.objects.filter()
    treinadores = Treinador.objects.filter()
    academias = Academia.objects.filter()
    context = {
        'academias': academias,
        'categories': categories,
        'treinadores': treinadores,
        'academia_categories': academia_categories,
        'academia_treinadores': academia_treinadores
    }
    return render(request, template_name, context)

@login_required(login_url='/contas/login/')
def edit_academia(request, id_academia):
    template_name = 'academias/add_academia.html'
    context ={}
    academia = get_object_or_404(Academia, id=id_academia)
    if request.method == 'POST':
        form = AcademiaForm(request.POST, instance=academia)
        if form.is_valid():
            form.save()
            return redirect('academias:list_academias')
    form = AcademiaForm(instance=academia)
    context['form'] = form
    return render(request, template_name, context)

@login_required(login_url='/contas/login/')
def delete_academia(request, id_academia):
    academia = Academia.objects.get(id=id_academia)
    academia.delete()
    return redirect('academias:list_academias')

templates/academias/add_academia.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block title %}

    Adicionar Academia - {{ block.super }}

{% endblock title %}

{% block body %}

    <div class="container">
        <br />
    <h5><b>Cadastro de Academia</b></h5>
        <div class="row">
            <div class ="col-md-12">
                <form action="" method="POST">
                {% csrf_token %}
                <div class="form-group">
                   <label for="{{ form.name.id_for_label }}">Nome</label>
                   {{ form.name|add_class:"form-control" }}
                </div>
                <div class="form-group">
                    <label for="{{ form.address.id_for_label }}">Endereco</label>
                    {{ form.address|add_class:"form-control" }}
                </div>
                <div class="form-group">
                  <label for="{{ form.cidade.id_for_label }}">Cidade</label>
                  {{ form.cidade|add_class:"form-control" }}
                </div>
                <div class="form-group">
                    <label for="{{ form.academia_category.id_for_label }}">Categorias Disponiveis</label>
                    {{ form.academia_category|add_class:"form-control" }}
                </div>
                <div class="form-group">
                    <label for="{{ form.academia_treinador.id_for_label }}">Treinadores</label>
                    {{ form.academia_treinador|add_class:"form-control" }}
                </div>
                    <button type="submit" class="btn btn-primary">Salvar</button>       
                </form>
            </div>
        </div>
    </div>

{% endblock body %}

templates/academias/list_academias.html
{% extends 'base.html' %}

{% block title %}

    Lista de Academias - {{ block.super }}

{% endblock title %}

{% block body %}

    <div class="container">
        <br />
        <h5><b>Lista de Academias</b></h5>
        <div class="row">
            <div class ="col-md-12">
                <br />
                    <a href="{% url 'academias:add_academia' %}">Cadastro de nova academia</a>
                <br />
                <br />
                <table class="table table-hover">
                <thead>
                    <tr>
                    <th scope="col">#</th>
                    <th scope="col">Nome</th>
                    <th scope="col">Endereco</th>
                    <th scope="col">Cidade</th>
                    <th scope="col">Categoria</th>
                    <th scope="col">Treinadores</th>
                    <th scope="col"></th>
                    <th scope="col"></th>
                    <th scope="col"></th>
                    </tr>
                </thead>
                <tbody>
                    {% for academia in academias %}
                        <tr>
                            <th scope="row">{{ academia.id }}</th>
                            <td>{{ academia.name }}</td>
                            <td>{{ academia.address }}</td>
                            <td>{{ academia.cidade }}</td>
                            <td>
                                {% for academia_category in academia_categories %}
                                    {% if academia_category.academia_id == academia.id %}
                                        <li>{{ academia_category.category }}</li>
                                    {% endif %}
                                {% endfor %}
                            </td>
                            <td>
                                {% for academia_treinador in academia_treinadores %}
                                    {% if academia_treinador.academia_id == academia.id %}
                                        <li>{{ academia_treinador.treinador }}</li>
                                    {% endif %}
                                {% endfor %}
                            </td>
                            <td>
                                <a href="{% url 'academias:edit_academia' academia.id %}" class="btn btn-primary btn-sm">Editar</a>
                            </td>
                            <td>
                                <a href="{% url 'academias:delete_academia' academia.id %}" class="btn btn-danger btn-sm ">Excluir</a>
                            </td>
                        </tr> 
                    {% endfor %}
                </tbody>
                </table>
            </div>
        </div>
    </div>

{% endblock body %}