academiaapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path('categorias/', include('categories.urls', namespace='categories')),
    path('aparelhos/', include('aparelhos.urls', namespace='aparelhos')),
    path('treinadores/', include('treinadores.urls', namespace='treinadores')),
    path('academias/', include('academias.urls', namespace='academias')),
    path('contas/', include('accounts.urls', namespace='accounts')),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/treinadores/urls.py
from django.urls import path
from . import views

app_name = 'treinadores'

urlpatterns = [
    path('', views.list_treinadores, name='list_treinadores'),
    path('adicionar/', views.add_treinador, name='add_treinador'),
    path('editar/<int:id_treinador>/', views.edit_treinador, name='edit_treinador'),
    path('excluir/<int:id_treinador>/', views.delete_treinador, name='delete_treinador'),
    path('buscar/', views.search_treinadores, name='search_treinadores'),
]

apps/treinadores/models.py
from django.db import models
from categories.models import Category

# Create your models here.
class Treinador(models.Model):
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    name = models.CharField('Nome', max_length=50)
    GENDER_CHOICES = (
        ('M', 'Masculino'),
        ('F', 'Feminino'),
        ('O', 'Outro'),
    )
    gender = models.CharField('Genero', max_length=1, choices=GENDER_CHOICES)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    
    class Meta:
        verbose_name = 'Treinador'
        verbose_name_plural = 'Treinadores'
        ordering =['id']

    def __str__(self):
        return self.name

apps/treinadores/forms.py
from django import forms
from .models import Treinador

class TreinadorForm(forms.ModelForm):

    class Meta:
        model = Treinador
        exclude = ('created_on' , 'updated_on',)

apps/treinadores/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .forms import TreinadorForm
from .models import Treinador, Category
from django.contrib.auth.decorators import login_required

# Create your views here.
@login_required(login_url='/contas/login/')
def add_treinador(request):
    template_name = 'treinadores/add_treinador.html'
    context = {}
    if request.method == 'POST':
        form = TreinadorForm(request.POST, request.FILES)
        if form.is_valid():
            f = form.save(commit=False)
            f.save()
            form.save_m2m()
            return redirect('treinadores:list_treinadores')
    form = TreinadorForm()
    context['form'] = form
    return render(request, template_name, context)

def list_treinadores(request):
    template_name = 'treinadores/list_treinadores.html'
    treinadores = Treinador.objects.filter()
    context = {
        'treinadores': treinadores
    }
    return render(request, template_name, context)

@login_required(login_url='/contas/login/')
def edit_treinador(request, id_treinador):
    template_name = 'treinadores/add_treinador.html'
    context ={}
    treinador = get_object_or_404(Treinador, id=id_treinador)
    if request.method == 'POST':
        form = TreinadorForm(request.POST, request.FILES,  instance=treinador)
        if form.is_valid():
            form.save()
            return redirect('treinadores:list_treinadores')
    form = TreinadorForm(instance=treinador)
    context['form'] = form
    return render(request, template_name, context)

@login_required(login_url='/contas/login/')
def delete_treinador(request, id_treinador):
    treinador = Treinador.objects.get(id=id_treinador)
    treinador.delete()
    return redirect('treinadores:list_treinadores')

def search_treinadores(request):
    template_name = 'treinadores/list_treinadores.html'
    query = request.GET.get('query')
    categorias = Category.objects.filter()
    treinadores = Treinador.objects.filter(name__icontains=query)
    context = {
        'treinadores': treinadores,
        'categorias': categorias,
    }
    return render(request,template_name, context)

templates/treinadores/add_treinador.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block title %}

    Adicionar Treinador - {{ block.super }}

{% endblock title %}

{% block body %}

    <div class="container">
        <br />
    <h5><b>Cadastro de Treinador</b></h5>
        <div class="row">
            <div class ="col-md-12">
                <form action="" method="POST" enctype="multipart/form-data"> 
                {% csrf_token %}
                <div class="form-group">
                   <label for="{{ form.name.id_for_label }}">Nome</label>
                   {{ form.name|add_class:"form-control" }}
                </div>
                <div class="form-group">
                    <label for="{{ form.gender.id_for_label }}">Genero</label>
                    {{ form.gender|add_class:"form-control" }}
                </div>
                <div class="form-group">
                    <label for="{{ form.category.id_for_label }}">Categoria</label>
                    {{ form.category|add_class:"form-control" }}
                </div>
                    <button type="submit" class="btn btn-primary">Salvar</button>       
                </form>
            </div>
        </div>
    </div>

{% endblock body %}

templates/treinadores/list_treinadores.html
{% extends 'base.html' %}

{% block title %}

    Lista de Treinadores - {{ block.super }}

{% endblock title %}

{% block body %}

    <div class="container">
        <br />
        <h5><b>Lista de Treinadores</b></h5>
        <div class="row">
            <div class ="col-md-12">
                <br />
                    <a href="{% url 'treinadores:add_treinador' %}">Cadastro de novo treinador</a>
                <br />
                <br />
                <table class="table table-hover">
                <thead>
                    <tr>
                    <th scope="col">#</th>
                    <th scope="col">Nome</th>
                    <th scope="col">Genero</th>
                    <th scope="col">Aula</th>
                    <th scope="col"></th>
                    <th scope="col"></th>
                    </tr>
                </thead>
                <tbody>
                    {% for treinador in treinadores %}
                        <tr>
                            <th scope="row">{{ treinador.id }}</th>
                            <td>{{ treinador.name }}</td>
                            <td>{{ treinador.gender }}</td>
                            <td>{{ treinador.category }}</td>
                            <td>
                                <a href="{% url 'treinadores:edit_treinador' treinador.id %}" class="btn btn-primary btn-sm">Editar</a>
                            </td>
                            <td>    
                                <a href="{% url 'treinadores:delete_treinador' treinador.id %}" class="btn btn-danger btn-sm ">Excluir</a>
                            </td>
                        </tr> 
                    {% endfor %}
                </tbody>
                </table>
            </div>
        </div>
    </div>

{% endblock body %}